services:
  - type: web
    name: carteira-da-turma
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
