# Generated by Django 5.2.17 on 2026-08-28 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_classroom_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nature', models.CharField(choices=[('credit', 'Recompensa'), ('debit', 'Despesa')], max_length=6)),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('default_key', models.CharField(max_length=80)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='wallet.classroom')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='wallet.classroomaction'),
        ),
        migrations.AddConstraint(
            model_name='classroomaction',
            constraint=models.UniqueConstraint(fields=('classroom', 'default_key'), name='unique_action_key_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='classroomaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='classroom_action_value_positive'),
        ),
    ]
